/*
 * Share my Cart
 *
 * Stay home. Stay safe. I'll bring your groceries along as I get mine. 
 *
 * API version: 0.1.0
 * Contact: sharemycart@beimir.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShoppingList struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	Type_ string `json:"type"`

	Items []ShoppingListItem `json:"items,omitempty"`
}
