/*
 * Share my Cart
 *
 * Stay home. Stay safe. I'll bring your groceries along as I get mine. 
 *
 * API version: 0.1.0
 * Contact: sharemycart@beimir.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddUser",
		strings.ToUpper("Post"),
		"/accounts",
		AddUser,
	},

	Route{
		"EmailVerification",
		strings.ToUpper("Post"),
		"/accounts/verifications",
		EmailVerification,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Delete"),
		"/sessions",
		LogoutUser,
	},

	Route{
		"ResetPassword",
		strings.ToUpper("Post"),
		"/accounts/verifications/{token}",
		ResetPassword,
	},

	Route{
		"UserLogin",
		strings.ToUpper("Post"),
		"/sessions",
		UserLogin,
	},

	Route{
		"AddNeedList",
		strings.ToUpper("Post"),
		"/needs",
		AddNeedList,
	},

	Route{
		"AddNeededItem",
		strings.ToUpper("Post"),
		"/needs/{id}",
		AddNeededItem,
	},

	Route{
		"AddNeededItemToShoppingListItem",
		strings.ToUpper("Post"),
		"/shoppinglists/{id}/items/{item_id}/need",
		AddNeededItemToShoppingListItem,
	},

	Route{
		"AddShoppingList",
		strings.ToUpper("Post"),
		"/shoppinglists",
		AddShoppingList,
	},

	Route{
		"AddShoppingListItem",
		strings.ToUpper("Post"),
		"/shoppinglists/{id}/items",
		AddShoppingListItem,
	},

	Route{
		"DeleteNeededItem",
		strings.ToUpper("Delete"),
		"/needs/{item_id}",
		DeleteNeededItem,
	},

	Route{
		"DeleteNeeds",
		strings.ToUpper("Delete"),
		"/needs/{id}",
		DeleteNeeds,
	},

	Route{
		"DeleteShoppingList",
		strings.ToUpper("Delete"),
		"/shoppinglists/{id}",
		DeleteShoppingList,
	},

	Route{
		"DeleteShoppingListItem",
		strings.ToUpper("Delete"),
		"/shoppinglists/{id}/items/{item_id}",
		DeleteShoppingListItem,
	},

	Route{
		"GetNeedLists",
		strings.ToUpper("Get"),
		"/needs",
		GetNeedLists,
	},

	Route{
		"GetNeeds",
		strings.ToUpper("Get"),
		"/needs/{id}",
		GetNeeds,
	},

	Route{
		"GetShoppingListItems",
		strings.ToUpper("Get"),
		"/shoppinglists/{id}",
		GetShoppingListItems,
	},

	Route{
		"GetShoppingLists",
		strings.ToUpper("Get"),
		"/shoppinglists",
		GetShoppingLists,
	},

	Route{
		"UpdateNeededItem",
		strings.ToUpper("Put"),
		"/needs/{item_id}",
		UpdateNeededItem,
	},

	Route{
		"UpdateShoppingList",
		strings.ToUpper("Put"),
		"/shoppinglists/{id}",
		UpdateShoppingList,
	},

	Route{
		"UpdateShoppingListItem",
		strings.ToUpper("Put"),
		"/shoppinglists/{id}/items/{item_id}",
		UpdateShoppingListItem,
	},

	Route{
		"AddNeedList",
		strings.ToUpper("Post"),
		"/needs",
		AddNeedList,
	},

	Route{
		"GetNeedLists",
		strings.ToUpper("Get"),
		"/needs",
		GetNeedLists,
	},

	Route{
		"AddShoppingList",
		strings.ToUpper("Post"),
		"/shoppinglists",
		AddShoppingList,
	},

	Route{
		"DeleteShoppingList",
		strings.ToUpper("Delete"),
		"/shoppinglists/{id}",
		DeleteShoppingList,
	},

	Route{
		"GetShoppingListItems",
		strings.ToUpper("Get"),
		"/shoppinglists/{id}",
		GetShoppingListItems,
	},

	Route{
		"GetShoppingListItems_0",
		strings.ToUpper("Get"),
		"/shoppinglists/{id}",
		GetShoppingListItems_0,
	},

	Route{
		"GetShoppingLists",
		strings.ToUpper("Get"),
		"/shoppinglists",
		GetShoppingLists,
	},

	Route{
		"UpdateShoppingList",
		strings.ToUpper("Put"),
		"/shoppinglists/{id}",
		UpdateShoppingList,
	},

	Route{
		"AddShoppingListItem",
		strings.ToUpper("Post"),
		"/shoppinglists/{id}/items",
		AddShoppingListItem,
	},

	Route{
		"DeleteShoppingListItem",
		strings.ToUpper("Delete"),
		"/shoppinglists/{id}/items/{item_id}",
		DeleteShoppingListItem,
	},

	Route{
		"UpdateShoppingListItem",
		strings.ToUpper("Put"),
		"/shoppinglists/{id}/items/{item_id}",
		UpdateShoppingListItem,
	},
}
