/*
 * Share my Cart
 *
 * Stay home. Stay safe. I'll bring your groceries along as I get mine.
 *
 * API version: 0.1.0
 * Contact: sharemycart@beimir.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
	Firebase    Firebase
}

type Routes []Route

// NewRouter returns a new mux.Router
func (firebase *Firebase) NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	routes := getRouteSlice(firebase)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func (firebase *Firebase) Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

func getRouteSlice(firebase *Firebase) Routes {
	var routes = Routes{
		Route{
			"Index",
			"GET",
			"/",
			firebase.Index,
			*firebase,
		},

		Route{
			"AddUser",
			strings.ToUpper("Post"),
			"/accounts",
			firebase.AddUser,
			*firebase,
		},

		Route{
			"EmailVerification",
			strings.ToUpper("Post"),
			"/accounts/verifications",
			firebase.EmailVerification,
			*firebase,
		},

		Route{
			"LogoutUser",
			strings.ToUpper("Delete"),
			"/sessions",
			firebase.LogoutUser,
			*firebase,
		},

		Route{
			"ResetPassword",
			strings.ToUpper("Post"),
			"/accounts/verifications/{token}",
			firebase.ResetPassword,
			*firebase,
		},

		Route{
			"UserLogin",
			strings.ToUpper("Post"),
			"/sessions",
			firebase.UserLogin,
			*firebase,
		},

		Route{
			"AddNeedList",
			strings.ToUpper("Post"),
			"/needs",
			firebase.AddNeedList,
			*firebase,
		},

		Route{
			"AddNeededItem",
			strings.ToUpper("Post"),
			"/needs/{id}",
			firebase.AddNeededItem,
			*firebase,
		},

		Route{
			"AddNeededItemToShoppingListItem",
			strings.ToUpper("Post"),
			"/shoppinglists/{id}/items/{item_id}/need",
			firebase.AddNeededItemToShoppingListItem,
			*firebase,
		},

		Route{
			"AddShoppingList",
			strings.ToUpper("Post"),
			"/shoppinglists",
			firebase.AddShoppingList,
			*firebase,
		},

		Route{
			"AddShoppingListItem",
			strings.ToUpper("Post"),
			"/shoppinglists/{id}/items",
			firebase.AddShoppingListItem,
			*firebase,
		},

		Route{
			"DeleteNeededItem",
			strings.ToUpper("Delete"),
			"/needs/{item_id}",
			firebase.DeleteNeededItem,
			*firebase,
		},

		Route{
			"DeleteNeeds",
			strings.ToUpper("Delete"),
			"/needs/{id}",
			firebase.DeleteNeeds,
			*firebase,
		},

		Route{
			"DeleteShoppingList",
			strings.ToUpper("Delete"),
			"/shoppinglists/{id}",
			firebase.DeleteShoppingList,
			*firebase,
		},

		Route{
			"DeleteShoppingListItem",
			strings.ToUpper("Delete"),
			"/shoppinglists/{id}/items/{item_id}",
			firebase.DeleteShoppingListItem,
			*firebase,
		},

		Route{
			"GetNeedLists",
			strings.ToUpper("Get"),
			"/needs",
			firebase.GetNeedLists,
			*firebase,
		},

		Route{
			"GetNeeds",
			strings.ToUpper("Get"),
			"/needs/{id}",
			firebase.GetNeeds,
			*firebase,
		},

		Route{
			"GetShoppingListItems",
			strings.ToUpper("Get"),
			"/shoppinglists/{id}",
			firebase.GetShoppingListItems,
			*firebase,
		},

		Route{
			"GetShoppingLists",
			strings.ToUpper("Get"),
			"/shoppinglists",
			firebase.GetShoppingLists,
			*firebase,
		},

		Route{
			"UpdateNeededItem",
			strings.ToUpper("Put"),
			"/needs/{item_id}",
			firebase.UpdateNeededItem,
			*firebase,
		},

		Route{
			"UpdateShoppingList",
			strings.ToUpper("Put"),
			"/shoppinglists/{id}",
			firebase.UpdateShoppingList,
			*firebase,
		},

		Route{
			"UpdateShoppingListItem",
			strings.ToUpper("Put"),
			"/shoppinglists/{id}/items/{item_id}",
			firebase.UpdateShoppingListItem,
			*firebase,
		},

		Route{
			"AddNeedList",
			strings.ToUpper("Post"),
			"/needs",
			firebase.AddNeedList,
			*firebase,
		},

		Route{
			"GetNeedLists",
			strings.ToUpper("Get"),
			"/needs",
			firebase.GetNeedLists,
			*firebase,
		},

		Route{
			"AddShoppingList",
			strings.ToUpper("Post"),
			"/shoppinglists",
			firebase.AddShoppingList,
			*firebase,
		},

		Route{
			"DeleteShoppingList",
			strings.ToUpper("Delete"),
			"/shoppinglists/{id}",
			firebase.DeleteShoppingList,
			*firebase,
		},

		Route{
			"GetShoppingListItems",
			strings.ToUpper("Get"),
			"/shoppinglists/{id}",
			firebase.GetShoppingListItems,
			*firebase,
		},

		Route{
			"GetShoppingLists",
			strings.ToUpper("Get"),
			"/shoppinglists",
			firebase.GetShoppingLists,
			*firebase,
		},

		Route{
			"UpdateShoppingList",
			strings.ToUpper("Put"),
			"/shoppinglists/{id}",
			firebase.UpdateShoppingList,
			*firebase,
		},

		Route{
			"AddShoppingListItem",
			strings.ToUpper("Post"),
			"/shoppinglists/{id}/items",
			firebase.AddShoppingListItem,
			*firebase,
		},

		Route{
			"DeleteShoppingListItem",
			strings.ToUpper("Delete"),
			"/shoppinglists/{id}/items/{item_id}",
			firebase.DeleteShoppingListItem,
			*firebase,
		},

		Route{
			"UpdateShoppingListItem",
			strings.ToUpper("Put"),
			"/shoppinglists/{id}/items/{item_id}",
			firebase.UpdateShoppingListItem,
			*firebase,
		},
	}
	return routes
}
